/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do Full Stack Club
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type ListWorkoutPlansParams = {
active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive = typeof ListWorkoutPlansActive[keyof typeof ListWorkoutPlansActive];


export const ListWorkoutPlansActive = {
  true: 'true',
  false: 'false',
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl: string | null;
  estimatedDurationInSeconds: number;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekday = typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekday[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekday];


export const CreateWorkoutPlanBodyWorkoutDaysItemWeekday = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekday: CreateWorkoutPlanBodyWorkoutDaysItemWeekday;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekday = typeof CreateWorkoutPlan201WorkoutDaysItemWeekday[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekday];


export const CreateWorkoutPlan201WorkoutDaysItemWeekday = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekday: CreateWorkoutPlan201WorkoutDaysItemWeekday;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutDay200ExercisesItem[];
  weekDay: string;
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
};

export type CompleteWorkoutSession401 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession404 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: string;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
from: string;
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
to: string;
};

export type GetStats200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetMe200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /** @minimum 1 */
  weightInGrams: number;
  /** @minimum 1 */
  heightInCentimeters: number;
  /** @minimum 1 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTimezoneBody = {
  /** @minLength 1 */
  timezone: string;
};

export type UpsertUserTimezone200 = {
  userId: string;
  timezone: string;
};

export type UpsertUserTimezone401 = {
  error: string;
  code: string;
};

export type UpsertUserTimezone500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary List workout plans with optional active filter
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[]
  status: 200
}

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401
  status: 401
}

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500
  status: 500
}
    
export type listWorkoutPlansResponseSuccess = (listWorkoutPlansResponse200) & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (listWorkoutPlansResponse401 | listWorkoutPlansResponse500) & {
  headers: Headers;
};

export type listWorkoutPlansResponse = (listWorkoutPlansResponseSuccess | listWorkoutPlansResponseError)

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workout-plans/?${stringifiedParams}` : `/workout-plans/`
}

export const listWorkoutPlans = async (params?: ListWorkoutPlansParams, options?: RequestInit): Promise<listWorkoutPlansResponse> => {
  
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create a new workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201
  status: 201
}

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400
  status: 400
}

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401
  status: 401
}

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404
  status: 404
}

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500
  status: 500
}
    
export type createWorkoutPlanResponseSuccess = (createWorkoutPlanResponse201) & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (createWorkoutPlanResponse400 | createWorkoutPlanResponse401 | createWorkoutPlanResponse404 | createWorkoutPlanResponse500) & {
  headers: Headers;
};

export type createWorkoutPlanResponse = (createWorkoutPlanResponseSuccess | createWorkoutPlanResponseError)

export const getCreateWorkoutPlanUrl = () => {


  

  return `/workout-plans/`
}

export const createWorkoutPlan = async (createWorkoutPlanBody: CreateWorkoutPlanBody, options?: RequestInit): Promise<createWorkoutPlanResponse> => {
  
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWorkoutPlanBody,)
  }
);}



/**
 * @summary Get a workout plan by ID
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200
  status: 200
}

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401
  status: 401
}

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404
  status: 404
}

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500
  status: 500
}
    
export type getWorkoutPlanResponseSuccess = (getWorkoutPlanResponse200) & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (getWorkoutPlanResponse401 | getWorkoutPlanResponse404 | getWorkoutPlanResponse500) & {
  headers: Headers;
};

export type getWorkoutPlanResponse = (getWorkoutPlanResponseSuccess | getWorkoutPlanResponseError)

export const getGetWorkoutPlanUrl = (workoutPlanId: string,) => {


  

  return `/workout-plans/${workoutPlanId}`
}

export const getWorkoutPlan = async (workoutPlanId: string, options?: RequestInit): Promise<getWorkoutPlanResponse> => {
  
  return customFetch<getWorkoutPlanResponse>(getGetWorkoutPlanUrl(workoutPlanId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get a workout day with exercises and sessions
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200
  status: 200
}

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401
  status: 401
}

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404
  status: 404
}

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500
  status: 500
}
    
export type getWorkoutDayResponseSuccess = (getWorkoutDayResponse200) & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (getWorkoutDayResponse401 | getWorkoutDayResponse404 | getWorkoutDayResponse500) & {
  headers: Headers;
};

export type getWorkoutDayResponse = (getWorkoutDayResponseSuccess | getWorkoutDayResponseError)

export const getGetWorkoutDayUrl = (workoutPlanId: string,
    workoutDayId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`
}

export const getWorkoutDay = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<getWorkoutDayResponse> => {
  
  return customFetch<getWorkoutDayResponse>(getGetWorkoutDayUrl(workoutPlanId,workoutDayId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Start a workout session for a specific day
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201
  status: 201
}

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401
  status: 401
}

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404
  status: 404
}

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409
  status: 409
}

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422
  status: 422
}

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500
  status: 500
}
    
export type startWorkoutSessionResponseSuccess = (startWorkoutSessionResponse201) & {
  headers: Headers;
};
export type startWorkoutSessionResponseError = (startWorkoutSessionResponse401 | startWorkoutSessionResponse404 | startWorkoutSessionResponse409 | startWorkoutSessionResponse422 | startWorkoutSessionResponse500) & {
  headers: Headers;
};

export type startWorkoutSessionResponse = (startWorkoutSessionResponseSuccess | startWorkoutSessionResponseError)

export const getStartWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`
}

export const startWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<startWorkoutSessionResponse> => {
  
  return customFetch<startWorkoutSessionResponse>(getStartWorkoutSessionUrl(workoutPlanId,workoutDayId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Complete a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200
  status: 200
}

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401
  status: 401
}

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404
  status: 404
}

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500
  status: 500
}
    
export type completeWorkoutSessionResponseSuccess = (completeWorkoutSessionResponse200) & {
  headers: Headers;
};
export type completeWorkoutSessionResponseError = (completeWorkoutSessionResponse401 | completeWorkoutSessionResponse404 | completeWorkoutSessionResponse500) & {
  headers: Headers;
};

export type completeWorkoutSessionResponse = (completeWorkoutSessionResponseSuccess | completeWorkoutSessionResponseError)

export const getCompleteWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`
}

export const completeWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,
    completeWorkoutSessionBody: CompleteWorkoutSessionBody, options?: RequestInit): Promise<completeWorkoutSessionResponse> => {
  
  return customFetch<completeWorkoutSessionResponse>(getCompleteWorkoutSessionUrl(workoutPlanId,workoutDayId,sessionId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      completeWorkoutSessionBody,)
  }
);}



/**
 * @summary Get home page data for the authenticated user
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200
  status: 200
}

export type getHomeDataResponse401 = {
  data: GetHomeData401
  status: 401
}

export type getHomeDataResponse404 = {
  data: GetHomeData404
  status: 404
}

export type getHomeDataResponse500 = {
  data: GetHomeData500
  status: 500
}
    
export type getHomeDataResponseSuccess = (getHomeDataResponse200) & {
  headers: Headers;
};
export type getHomeDataResponseError = (getHomeDataResponse401 | getHomeDataResponse404 | getHomeDataResponse500) & {
  headers: Headers;
};

export type getHomeDataResponse = (getHomeDataResponseSuccess | getHomeDataResponseError)

export const getGetHomeDataUrl = (date: string,) => {


  

  return `/home/${date}`
}

export const getHomeData = async (date: string, options?: RequestInit): Promise<getHomeDataResponse> => {
  
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get workout statistics for a date range
 */
export type getStatsResponse200 = {
  data: GetStats200
  status: 200
}

export type getStatsResponse401 = {
  data: GetStats401
  status: 401
}

export type getStatsResponse500 = {
  data: GetStats500
  status: 500
}
    
export type getStatsResponseSuccess = (getStatsResponse200) & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse401 | getStatsResponse500) & {
  headers: Headers;
};

export type getStatsResponse = (getStatsResponseSuccess | getStatsResponseError)

export const getGetStatsUrl = (params: GetStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/stats/?${stringifiedParams}` : `/stats/`
}

export const getStats = async (params: GetStatsParams, options?: RequestInit): Promise<getStatsResponse> => {
  
  return customFetch<getStatsResponse>(getGetStatsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get authenticated user train data
 */
export type getMeResponse200 = {
  data: GetMe200
  status: 200
}

export type getMeResponse401 = {
  data: GetMe401
  status: 401
}

export type getMeResponse500 = {
  data: GetMe500
  status: 500
}
    
export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = (getMeResponseSuccess | getMeResponseError)

export const getGetMeUrl = () => {


  

  return `/me/`
}

export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {
  
  return customFetch<getMeResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create or update authenticated user train data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200
  status: 200
}

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401
  status: 401
}

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500
  status: 500
}
    
export type upsertUserTrainDataResponseSuccess = (upsertUserTrainDataResponse200) & {
  headers: Headers;
};
export type upsertUserTrainDataResponseError = (upsertUserTrainDataResponse401 | upsertUserTrainDataResponse500) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse = (upsertUserTrainDataResponseSuccess | upsertUserTrainDataResponseError)

export const getUpsertUserTrainDataUrl = () => {


  

  return `/me/`
}

export const upsertUserTrainData = async (upsertUserTrainDataBody: UpsertUserTrainDataBody, options?: RequestInit): Promise<upsertUserTrainDataResponse> => {
  
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertUserTrainDataBody,)
  }
);}



/**
 * @summary Create or update authenticated user timezone
 */
export type upsertUserTimezoneResponse200 = {
  data: UpsertUserTimezone200
  status: 200
}

export type upsertUserTimezoneResponse401 = {
  data: UpsertUserTimezone401
  status: 401
}

export type upsertUserTimezoneResponse500 = {
  data: UpsertUserTimezone500
  status: 500
}
    
export type upsertUserTimezoneResponseSuccess = (upsertUserTimezoneResponse200) & {
  headers: Headers;
};
export type upsertUserTimezoneResponseError = (upsertUserTimezoneResponse401 | upsertUserTimezoneResponse500) & {
  headers: Headers;
};

export type upsertUserTimezoneResponse = (upsertUserTimezoneResponseSuccess | upsertUserTimezoneResponseError)

export const getUpsertUserTimezoneUrl = () => {


  

  return `/me/timezone`
}

export const upsertUserTimezone = async (upsertUserTimezoneBody: UpsertUserTimezoneBody, options?: RequestInit): Promise<upsertUserTimezoneResponse> => {
  
  return customFetch<upsertUserTimezoneResponse>(getUpsertUserTimezoneUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertUserTimezoneBody,)
  }
);}



/**
 * @summary AI personal trainer chat endpoint
 */
export type chatWithAIResponse200 = {
  data: void
  status: 200
}
    
export type chatWithAIResponseSuccess = (chatWithAIResponse200) & {
  headers: Headers;
};
;

export type chatWithAIResponse = (chatWithAIResponseSuccess)

export const getChatWithAIUrl = () => {


  

  return `/ai/`
}

export const chatWithAI = async ( options?: RequestInit): Promise<chatWithAIResponse> => {
  
  return customFetch<chatWithAIResponse>(getChatWithAIUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Hello world endpoint
 */
export type getResponse200 = {
  data: Get200
  status: 200
}
    
export type getResponseSuccess = (getResponse200) & {
  headers: Headers;
};
;

export type getResponse = (getResponseSuccess)

export const getGetUrl = () => {


  

  return `/`
}

export const get = async ( options?: RequestInit): Promise<getResponse> => {
  
  return customFetch<getResponse>(getGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
