/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do Full Stack Club
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type ListWorkoutPlansParams = {
active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive = typeof ListWorkoutPlansActive[keyof typeof ListWorkoutPlansActive];


export const ListWorkoutPlansActive = {
  true: 'true',
  false: 'false',
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl: string | null;
  estimatedDurationInSeconds: number;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekday = typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekday[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekday];


export const CreateWorkoutPlanBodyWorkoutDaysItemWeekday = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekday: CreateWorkoutPlanBodyWorkoutDaysItemWeekday;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekday = typeof CreateWorkoutPlan201WorkoutDaysItemWeekday[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekday];


export const CreateWorkoutPlan201WorkoutDaysItemWeekday = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekday: CreateWorkoutPlan201WorkoutDaysItemWeekday;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutDay200ExercisesItem[];
  weekDay: string;
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
};

export type CompleteWorkoutSession401 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession404 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: string;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
from: string;
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
to: string;
};

export type GetStats200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetMe200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /** @minimum 1 */
  weightInGrams: number;
  /** @minimum 1 */
  heightInCentimeters: number;
  /** @minimum 1 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTimezoneBody = {
  /** @minLength 1 */
  timezone: string;
};

export type UpsertUserTimezone200 = {
  userId: string;
  timezone: string;
};

export type UpsertUserTimezone401 = {
  error: string;
  code: string;
};

export type UpsertUserTimezone500 = {
  error: string;
  code: string;
};

export type PairSmartwatchBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  deviceCode: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  deviceName: string;
};

export type PairSmartwatch200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  deviceCode: string;
  deviceName: string;
};

export type PairSmartwatch401 = {
  error: string;
  code: string;
};

export type PairSmartwatch409 = {
  error: string;
  code: string;
};

export type PairSmartwatch500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetSmartwatch200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  deviceCode: string;
  deviceName: string;
} | null;

export type GetSmartwatch401 = {
  error: string;
  code: string;
};

export type GetSmartwatch500 = {
  error: string;
  code: string;
};

export type DeleteSmartwatch200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
};

export type DeleteSmartwatch401 = {
  error: string;
  code: string;
};

export type DeleteSmartwatch404 = {
  error: string;
  code: string;
};

export type DeleteSmartwatch500 = {
  error: string;
  code: string;
};

export type GetWatchUserIdByDeviceCodeParams = {
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
deviceCode: string;
};

export type GetWatchUserIdByDeviceCode200 = {
  userId: string | 0;
};

export type GetWatchUserIdByDeviceCode500 = {
  error: string;
  code: string;
};

export type GetWatchActiveSessionParams = {
/**
 * @minLength 1
 */
userId: string;
};

export type Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWatchActiveSession200 = {
  active: boolean;
} | {
  active: boolean;
  /** @pattern ^(?:(?:\d\d[2468][048] | \d\d[13579][26] | \d\d0[48] | [02468][048]00 | [13579][26]00)-02-29 | \d{4}-(?:(?:0[13578] | 1[02])-(?:0[1-9] | [12]\d | 3[01]) | (?:0[469] | 11)-(?:0[1-9] | 30) | (?:02)-(?:0[1-9] | 1\d | 2[0-8])))T(?:(?:[01]\d | 2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048] | 2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  completedAt: string | null;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  workoutDayName: string;
  weekDay: string;
  isRest: boolean;
  exercises: Item[];
};

export type GetWatchActiveSession500 = {
  error: string;
  code: string;
};

export type GetWatchTodayWorkoutParams = {
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
deviceCode: string;
};

export type GetWatchTodayWorkout200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWatchTodayWorkout200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  workoutDayName: string;
  weekDay: string;
  isRest: boolean;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  completedAt: string | null;
  exercises: GetWatchTodayWorkout200ExercisesItem[];
};

export type GetWatchTodayWorkout404 = {
  error: string;
  code: string;
};

export type GetWatchTodayWorkout500 = {
  error: string;
  code: string;
};

export type StartWatchWorkoutSessionBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  deviceCode: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
};

export type StartWatchWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  completedAt: string | null;
};

export type StartWatchWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWatchWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWatchWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWatchWorkoutSession500 = {
  error: string;
  code: string;
};

export type CompleteWatchWorkoutSessionBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  deviceCode: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type CompleteWatchWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
};

export type CompleteWatchWorkoutSession404 = {
  error: string;
  code: string;
};

export type CompleteWatchWorkoutSession500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary List workout plans with optional active filter
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[]
  status: 200
}

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401
  status: 401
}

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500
  status: 500
}
    
export type listWorkoutPlansResponseSuccess = (listWorkoutPlansResponse200) & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (listWorkoutPlansResponse401 | listWorkoutPlansResponse500) & {
  headers: Headers;
};

export type listWorkoutPlansResponse = (listWorkoutPlansResponseSuccess | listWorkoutPlansResponseError)

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workout-plans/?${stringifiedParams}` : `/workout-plans/`
}

export const listWorkoutPlans = async (params?: ListWorkoutPlansParams, options?: RequestInit): Promise<listWorkoutPlansResponse> => {
  
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create a new workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201
  status: 201
}

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400
  status: 400
}

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401
  status: 401
}

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404
  status: 404
}

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500
  status: 500
}
    
export type createWorkoutPlanResponseSuccess = (createWorkoutPlanResponse201) & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (createWorkoutPlanResponse400 | createWorkoutPlanResponse401 | createWorkoutPlanResponse404 | createWorkoutPlanResponse500) & {
  headers: Headers;
};

export type createWorkoutPlanResponse = (createWorkoutPlanResponseSuccess | createWorkoutPlanResponseError)

export const getCreateWorkoutPlanUrl = () => {


  

  return `/workout-plans/`
}

export const createWorkoutPlan = async (createWorkoutPlanBody: CreateWorkoutPlanBody, options?: RequestInit): Promise<createWorkoutPlanResponse> => {
  
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWorkoutPlanBody,)
  }
);}



/**
 * @summary Get a workout plan by ID
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200
  status: 200
}

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401
  status: 401
}

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404
  status: 404
}

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500
  status: 500
}
    
export type getWorkoutPlanResponseSuccess = (getWorkoutPlanResponse200) & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (getWorkoutPlanResponse401 | getWorkoutPlanResponse404 | getWorkoutPlanResponse500) & {
  headers: Headers;
};

export type getWorkoutPlanResponse = (getWorkoutPlanResponseSuccess | getWorkoutPlanResponseError)

export const getGetWorkoutPlanUrl = (workoutPlanId: string,) => {


  

  return `/workout-plans/${workoutPlanId}`
}

export const getWorkoutPlan = async (workoutPlanId: string, options?: RequestInit): Promise<getWorkoutPlanResponse> => {
  
  return customFetch<getWorkoutPlanResponse>(getGetWorkoutPlanUrl(workoutPlanId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get a workout day with exercises and sessions
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200
  status: 200
}

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401
  status: 401
}

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404
  status: 404
}

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500
  status: 500
}
    
export type getWorkoutDayResponseSuccess = (getWorkoutDayResponse200) & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (getWorkoutDayResponse401 | getWorkoutDayResponse404 | getWorkoutDayResponse500) & {
  headers: Headers;
};

export type getWorkoutDayResponse = (getWorkoutDayResponseSuccess | getWorkoutDayResponseError)

export const getGetWorkoutDayUrl = (workoutPlanId: string,
    workoutDayId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`
}

export const getWorkoutDay = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<getWorkoutDayResponse> => {
  
  return customFetch<getWorkoutDayResponse>(getGetWorkoutDayUrl(workoutPlanId,workoutDayId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Start a workout session for a specific day
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201
  status: 201
}

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401
  status: 401
}

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404
  status: 404
}

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409
  status: 409
}

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422
  status: 422
}

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500
  status: 500
}
    
export type startWorkoutSessionResponseSuccess = (startWorkoutSessionResponse201) & {
  headers: Headers;
};
export type startWorkoutSessionResponseError = (startWorkoutSessionResponse401 | startWorkoutSessionResponse404 | startWorkoutSessionResponse409 | startWorkoutSessionResponse422 | startWorkoutSessionResponse500) & {
  headers: Headers;
};

export type startWorkoutSessionResponse = (startWorkoutSessionResponseSuccess | startWorkoutSessionResponseError)

export const getStartWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`
}

export const startWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<startWorkoutSessionResponse> => {
  
  return customFetch<startWorkoutSessionResponse>(getStartWorkoutSessionUrl(workoutPlanId,workoutDayId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Complete a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200
  status: 200
}

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401
  status: 401
}

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404
  status: 404
}

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500
  status: 500
}
    
export type completeWorkoutSessionResponseSuccess = (completeWorkoutSessionResponse200) & {
  headers: Headers;
};
export type completeWorkoutSessionResponseError = (completeWorkoutSessionResponse401 | completeWorkoutSessionResponse404 | completeWorkoutSessionResponse500) & {
  headers: Headers;
};

export type completeWorkoutSessionResponse = (completeWorkoutSessionResponseSuccess | completeWorkoutSessionResponseError)

export const getCompleteWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`
}

export const completeWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,
    completeWorkoutSessionBody: CompleteWorkoutSessionBody, options?: RequestInit): Promise<completeWorkoutSessionResponse> => {
  
  return customFetch<completeWorkoutSessionResponse>(getCompleteWorkoutSessionUrl(workoutPlanId,workoutDayId,sessionId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      completeWorkoutSessionBody,)
  }
);}



/**
 * @summary Get home page data for the authenticated user
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200
  status: 200
}

export type getHomeDataResponse401 = {
  data: GetHomeData401
  status: 401
}

export type getHomeDataResponse404 = {
  data: GetHomeData404
  status: 404
}

export type getHomeDataResponse500 = {
  data: GetHomeData500
  status: 500
}
    
export type getHomeDataResponseSuccess = (getHomeDataResponse200) & {
  headers: Headers;
};
export type getHomeDataResponseError = (getHomeDataResponse401 | getHomeDataResponse404 | getHomeDataResponse500) & {
  headers: Headers;
};

export type getHomeDataResponse = (getHomeDataResponseSuccess | getHomeDataResponseError)

export const getGetHomeDataUrl = (date: string,) => {


  

  return `/home/${date}`
}

export const getHomeData = async (date: string, options?: RequestInit): Promise<getHomeDataResponse> => {
  
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get workout statistics for a date range
 */
export type getStatsResponse200 = {
  data: GetStats200
  status: 200
}

export type getStatsResponse401 = {
  data: GetStats401
  status: 401
}

export type getStatsResponse500 = {
  data: GetStats500
  status: 500
}
    
export type getStatsResponseSuccess = (getStatsResponse200) & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse401 | getStatsResponse500) & {
  headers: Headers;
};

export type getStatsResponse = (getStatsResponseSuccess | getStatsResponseError)

export const getGetStatsUrl = (params: GetStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/stats/?${stringifiedParams}` : `/stats/`
}

export const getStats = async (params: GetStatsParams, options?: RequestInit): Promise<getStatsResponse> => {
  
  return customFetch<getStatsResponse>(getGetStatsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get authenticated user train data
 */
export type getMeResponse200 = {
  data: GetMe200
  status: 200
}

export type getMeResponse401 = {
  data: GetMe401
  status: 401
}

export type getMeResponse500 = {
  data: GetMe500
  status: 500
}
    
export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = (getMeResponseSuccess | getMeResponseError)

export const getGetMeUrl = () => {


  

  return `/me/`
}

export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {
  
  return customFetch<getMeResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create or update authenticated user train data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200
  status: 200
}

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401
  status: 401
}

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500
  status: 500
}
    
export type upsertUserTrainDataResponseSuccess = (upsertUserTrainDataResponse200) & {
  headers: Headers;
};
export type upsertUserTrainDataResponseError = (upsertUserTrainDataResponse401 | upsertUserTrainDataResponse500) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse = (upsertUserTrainDataResponseSuccess | upsertUserTrainDataResponseError)

export const getUpsertUserTrainDataUrl = () => {


  

  return `/me/`
}

export const upsertUserTrainData = async (upsertUserTrainDataBody: UpsertUserTrainDataBody, options?: RequestInit): Promise<upsertUserTrainDataResponse> => {
  
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertUserTrainDataBody,)
  }
);}



/**
 * @summary Create or update authenticated user timezone
 */
export type upsertUserTimezoneResponse200 = {
  data: UpsertUserTimezone200
  status: 200
}

export type upsertUserTimezoneResponse401 = {
  data: UpsertUserTimezone401
  status: 401
}

export type upsertUserTimezoneResponse500 = {
  data: UpsertUserTimezone500
  status: 500
}
    
export type upsertUserTimezoneResponseSuccess = (upsertUserTimezoneResponse200) & {
  headers: Headers;
};
export type upsertUserTimezoneResponseError = (upsertUserTimezoneResponse401 | upsertUserTimezoneResponse500) & {
  headers: Headers;
};

export type upsertUserTimezoneResponse = (upsertUserTimezoneResponseSuccess | upsertUserTimezoneResponseError)

export const getUpsertUserTimezoneUrl = () => {


  

  return `/me/timezone`
}

export const upsertUserTimezone = async (upsertUserTimezoneBody: UpsertUserTimezoneBody, options?: RequestInit): Promise<upsertUserTimezoneResponse> => {
  
  return customFetch<upsertUserTimezoneResponse>(getUpsertUserTimezoneUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertUserTimezoneBody,)
  }
);}



/**
 * @summary Create or update smartwatch pairing for the authenticated user
 */
export type pairSmartwatchResponse200 = {
  data: PairSmartwatch200
  status: 200
}

export type pairSmartwatchResponse401 = {
  data: PairSmartwatch401
  status: 401
}

export type pairSmartwatchResponse409 = {
  data: PairSmartwatch409
  status: 409
}

export type pairSmartwatchResponse500 = {
  data: PairSmartwatch500
  status: 500
}
    
export type pairSmartwatchResponseSuccess = (pairSmartwatchResponse200) & {
  headers: Headers;
};
export type pairSmartwatchResponseError = (pairSmartwatchResponse401 | pairSmartwatchResponse409 | pairSmartwatchResponse500) & {
  headers: Headers;
};

export type pairSmartwatchResponse = (pairSmartwatchResponseSuccess | pairSmartwatchResponseError)

export const getPairSmartwatchUrl = () => {


  

  return `/smartwatch/pair`
}

export const pairSmartwatch = async (pairSmartwatchBody: PairSmartwatchBody, options?: RequestInit): Promise<pairSmartwatchResponse> => {
  
  return customFetch<pairSmartwatchResponse>(getPairSmartwatchUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pairSmartwatchBody,)
  }
);}



/**
 * @summary Get smartwatch pairing for the authenticated user
 */
export type getSmartwatchResponse200 = {
  data: GetSmartwatch200
  status: 200
}

export type getSmartwatchResponse401 = {
  data: GetSmartwatch401
  status: 401
}

export type getSmartwatchResponse500 = {
  data: GetSmartwatch500
  status: 500
}
    
export type getSmartwatchResponseSuccess = (getSmartwatchResponse200) & {
  headers: Headers;
};
export type getSmartwatchResponseError = (getSmartwatchResponse401 | getSmartwatchResponse500) & {
  headers: Headers;
};

export type getSmartwatchResponse = (getSmartwatchResponseSuccess | getSmartwatchResponseError)

export const getGetSmartwatchUrl = () => {


  

  return `/smartwatch/`
}

export const getSmartwatch = async ( options?: RequestInit): Promise<getSmartwatchResponse> => {
  
  return customFetch<getSmartwatchResponse>(getGetSmartwatchUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Delete smartwatch pairing for the authenticated user
 */
export type deleteSmartwatchResponse200 = {
  data: DeleteSmartwatch200
  status: 200
}

export type deleteSmartwatchResponse401 = {
  data: DeleteSmartwatch401
  status: 401
}

export type deleteSmartwatchResponse404 = {
  data: DeleteSmartwatch404
  status: 404
}

export type deleteSmartwatchResponse500 = {
  data: DeleteSmartwatch500
  status: 500
}
    
export type deleteSmartwatchResponseSuccess = (deleteSmartwatchResponse200) & {
  headers: Headers;
};
export type deleteSmartwatchResponseError = (deleteSmartwatchResponse401 | deleteSmartwatchResponse404 | deleteSmartwatchResponse500) & {
  headers: Headers;
};

export type deleteSmartwatchResponse = (deleteSmartwatchResponseSuccess | deleteSmartwatchResponseError)

export const getDeleteSmartwatchUrl = () => {


  

  return `/smartwatch/`
}

export const deleteSmartwatch = async ( options?: RequestInit): Promise<deleteSmartwatchResponse> => {
  
  return customFetch<deleteSmartwatchResponse>(getDeleteSmartwatchUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get user id by smartwatch device code
 */
export type getWatchUserIdByDeviceCodeResponse200 = {
  data: GetWatchUserIdByDeviceCode200
  status: 200
}

export type getWatchUserIdByDeviceCodeResponse500 = {
  data: GetWatchUserIdByDeviceCode500
  status: 500
}
    
export type getWatchUserIdByDeviceCodeResponseSuccess = (getWatchUserIdByDeviceCodeResponse200) & {
  headers: Headers;
};
export type getWatchUserIdByDeviceCodeResponseError = (getWatchUserIdByDeviceCodeResponse500) & {
  headers: Headers;
};

export type getWatchUserIdByDeviceCodeResponse = (getWatchUserIdByDeviceCodeResponseSuccess | getWatchUserIdByDeviceCodeResponseError)

export const getGetWatchUserIdByDeviceCodeUrl = (params: GetWatchUserIdByDeviceCodeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/watch/user-id?${stringifiedParams}` : `/watch/user-id`
}

export const getWatchUserIdByDeviceCode = async (params: GetWatchUserIdByDeviceCodeParams, options?: RequestInit): Promise<getWatchUserIdByDeviceCodeResponse> => {
  
  return customFetch<getWatchUserIdByDeviceCodeResponse>(getGetWatchUserIdByDeviceCodeUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get active workout session for a user and date
 */
export type getWatchActiveSessionResponse200 = {
  data: GetWatchActiveSession200
  status: 200
}

export type getWatchActiveSessionResponse500 = {
  data: GetWatchActiveSession500
  status: 500
}
    
export type getWatchActiveSessionResponseSuccess = (getWatchActiveSessionResponse200) & {
  headers: Headers;
};
export type getWatchActiveSessionResponseError = (getWatchActiveSessionResponse500) & {
  headers: Headers;
};

export type getWatchActiveSessionResponse = (getWatchActiveSessionResponseSuccess | getWatchActiveSessionResponseError)

export const getGetWatchActiveSessionUrl = (date: string,
    params: GetWatchActiveSessionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/watch/sessions/active/${date}?${stringifiedParams}` : `/watch/sessions/active/${date}`
}

export const getWatchActiveSession = async (date: string,
    params: GetWatchActiveSessionParams, options?: RequestInit): Promise<getWatchActiveSessionResponse> => {
  
  return customFetch<getWatchActiveSessionResponse>(getGetWatchActiveSessionUrl(date,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get active plan workout for a specific date using device code
 */
export type getWatchTodayWorkoutResponse200 = {
  data: GetWatchTodayWorkout200
  status: 200
}

export type getWatchTodayWorkoutResponse404 = {
  data: GetWatchTodayWorkout404
  status: 404
}

export type getWatchTodayWorkoutResponse500 = {
  data: GetWatchTodayWorkout500
  status: 500
}
    
export type getWatchTodayWorkoutResponseSuccess = (getWatchTodayWorkoutResponse200) & {
  headers: Headers;
};
export type getWatchTodayWorkoutResponseError = (getWatchTodayWorkoutResponse404 | getWatchTodayWorkoutResponse500) & {
  headers: Headers;
};

export type getWatchTodayWorkoutResponse = (getWatchTodayWorkoutResponseSuccess | getWatchTodayWorkoutResponseError)

export const getGetWatchTodayWorkoutUrl = (date: string,
    params: GetWatchTodayWorkoutParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/watch/today/${date}?${stringifiedParams}` : `/watch/today/${date}`
}

export const getWatchTodayWorkout = async (date: string,
    params: GetWatchTodayWorkoutParams, options?: RequestInit): Promise<getWatchTodayWorkoutResponse> => {
  
  return customFetch<getWatchTodayWorkoutResponse>(getGetWatchTodayWorkoutUrl(date,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Start workout session using smartwatch device code
 */
export type startWatchWorkoutSessionResponse201 = {
  data: StartWatchWorkoutSession201
  status: 201
}

export type startWatchWorkoutSessionResponse404 = {
  data: StartWatchWorkoutSession404
  status: 404
}

export type startWatchWorkoutSessionResponse409 = {
  data: StartWatchWorkoutSession409
  status: 409
}

export type startWatchWorkoutSessionResponse422 = {
  data: StartWatchWorkoutSession422
  status: 422
}

export type startWatchWorkoutSessionResponse500 = {
  data: StartWatchWorkoutSession500
  status: 500
}
    
export type startWatchWorkoutSessionResponseSuccess = (startWatchWorkoutSessionResponse201) & {
  headers: Headers;
};
export type startWatchWorkoutSessionResponseError = (startWatchWorkoutSessionResponse404 | startWatchWorkoutSessionResponse409 | startWatchWorkoutSessionResponse422 | startWatchWorkoutSessionResponse500) & {
  headers: Headers;
};

export type startWatchWorkoutSessionResponse = (startWatchWorkoutSessionResponseSuccess | startWatchWorkoutSessionResponseError)

export const getStartWatchWorkoutSessionUrl = () => {


  

  return `/watch/sessions/start`
}

export const startWatchWorkoutSession = async (startWatchWorkoutSessionBody: StartWatchWorkoutSessionBody, options?: RequestInit): Promise<startWatchWorkoutSessionResponse> => {
  
  return customFetch<startWatchWorkoutSessionResponse>(getStartWatchWorkoutSessionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      startWatchWorkoutSessionBody,)
  }
);}



/**
 * @summary Complete workout session using smartwatch device code
 */
export type completeWatchWorkoutSessionResponse200 = {
  data: CompleteWatchWorkoutSession200
  status: 200
}

export type completeWatchWorkoutSessionResponse404 = {
  data: CompleteWatchWorkoutSession404
  status: 404
}

export type completeWatchWorkoutSessionResponse500 = {
  data: CompleteWatchWorkoutSession500
  status: 500
}
    
export type completeWatchWorkoutSessionResponseSuccess = (completeWatchWorkoutSessionResponse200) & {
  headers: Headers;
};
export type completeWatchWorkoutSessionResponseError = (completeWatchWorkoutSessionResponse404 | completeWatchWorkoutSessionResponse500) & {
  headers: Headers;
};

export type completeWatchWorkoutSessionResponse = (completeWatchWorkoutSessionResponseSuccess | completeWatchWorkoutSessionResponseError)

export const getCompleteWatchWorkoutSessionUrl = (sessionId: string,) => {


  

  return `/watch/sessions/${sessionId}/finish`
}

export const completeWatchWorkoutSession = async (sessionId: string,
    completeWatchWorkoutSessionBody: CompleteWatchWorkoutSessionBody, options?: RequestInit): Promise<completeWatchWorkoutSessionResponse> => {
  
  return customFetch<completeWatchWorkoutSessionResponse>(getCompleteWatchWorkoutSessionUrl(sessionId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      completeWatchWorkoutSessionBody,)
  }
);}



/**
 * @summary AI personal trainer chat endpoint
 */
export type chatWithAIResponse200 = {
  data: void
  status: 200
}
    
export type chatWithAIResponseSuccess = (chatWithAIResponse200) & {
  headers: Headers;
};
;

export type chatWithAIResponse = (chatWithAIResponseSuccess)

export const getChatWithAIUrl = () => {


  

  return `/ai/`
}

export const chatWithAI = async ( options?: RequestInit): Promise<chatWithAIResponse> => {
  
  return customFetch<chatWithAIResponse>(getChatWithAIUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Hello world endpoint
 */
export type getResponse200 = {
  data: Get200
  status: 200
}
    
export type getResponseSuccess = (getResponse200) & {
  headers: Headers;
};
;

export type getResponse = (getResponseSuccess)

export const getGetUrl = () => {


  

  return `/`
}

export const get = async ( options?: RequestInit): Promise<getResponse> => {
  
  return customFetch<getResponse>(getGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
